### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by denisdulici** [akaunting/docker#13]
Hey there,

We're looking for maintainers to handle this repo and [docker hub](https://hub.docker.com/r/akaunting/akaunting) builds/images. Feel free to reply to this issue if you're interested.

Thanks in advance.

**Comment by bd8392** [comment]
Is someone experienced with akaunting here who wants to work with me on this?
```
FROM php:7.4-apache

RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libzip-dev \
    imagemagick \
    libmcrypt-dev \
    libpng-dev \
    libpq-dev \
    libxrender1 \
    locales \
    openssh-client \
    patch \
    unzip \
    zlib1g-dev \
    zip \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    gd \
    bcmath \
    pcntl \
    pdo \
    pdo_pgsql \
    pdo_mysql \
    zip

RUN docker-php-ext-configure gd --with-freetype --with-jpeg

RUN cp /usr/share/i18n/SUPPORTED /etc/locale.gen
RUN locale-gen

RUN wget -O akaunting.zip "https://akaunting.com/download.php?version=latest&utm_source=docker&utm_campaign=developers"
RUN mkdir -p /var/www/akaunting
RUN unzip akaunting.zip -d /var/www/akaunting
RUN rm akaunting.zip

RUN find /var/www/akaunting/ -type d -exec chmod 755 {} \;
RUN find /var/www/akaunting/ -type f -exec chmod 
```

**Comment by danielwilson654** [comment]
I'm pretty experienced with docker, done some really wacky stuff with it so
I know it's internals pretty well, but not akaunting. I can stay subscribed
to this thread and be a second pair of eyes on pull requests. if that helps
at all?

**Comment by denisdulici** [comment]
Thanks @bd8392 & @danielwilson654 for your help, lets wait for a lead maintainer.

**Comment by solacelost** [comment]
Hey, I'm not terribly interested in taking over as a lead maintainer, but if you really need one I could probably do it. I suppose your concerns about public GitHub history will apply to my personal account as well, so maybe not.

I've started running Akaunting for some things, and the lack of working Dockerfiles led me to just... do the whole thing myself.

I started with @bd8392 's paste, because I like TLS termination being consolidated at my load balancers so I can use wildcard certificates, and an all-in-one webserver build was most attractive to me. There are some problems with his Dockerfile, both in convention/efficiency as well as actually working when using a sensible volume mount.

Also, I don't use `docker`, but rather `podman` because I prefer daemonless, userns'd containers. I built a docker-compose.yml, but I haven't personally tested it. I think it should work.

I'll get a README up soon enough with some more detailed instructions than provided here. First launch in particular requires an extra environment variable or CLI flag to be passed. I built it just for myself, but figured someone here might like this as a launching point for a more, shall we say, working basis for this repository.

[Here](https://git.jharmison.com/jharmison/akaunting)'s a link to the repository.
[Here](https://harbor.jharmison.com/harbor/projects/11/repositories/akaunting)'s a link to the container registry I've pushed to.

The security scans don't look so great, but the CVEs appear to all be open in Ubuntu directly. I may desire to shift the base image to Fedora, and manage installation of Apache and PHP myself at a later date, but the work that's been done in the docker library image repos to make PHP behave makes me think that's a lot of rework.

For people just hoping for a docker-compose solution that works, this should do the trick for you:

```shell
git clone https://git.jharmison.com/jharmison/akaunting
cd akaunting
cp env/db.env.example env/db.env
vi env/db.env # and set things
cp env/run.env.example env/run.env
vi env/run.env # and set things

docker-compose up -d -e AKAUNTING_SETUP=true
```

then head to HTTP at port 8080 on the host you ran docker-compose from, configure the server as needed, and when done with initial setup:

```shell
docker-compose down -v
docker-compose up -d
```

The docker-compose.yml includes a watchtower container to automatically pull the latest images and restart whenever needed on an interval of 5 minutes. You may need to use `sudo` for `docker-compose`, because the docker socket is passed in to the watchtower container. You can optionally only `up` the `akaunting` and `akaunting-db` containers to avoid that possibility.

`podman` users can find a set of scripts in the `podman` directory, including one that will create systemd unit files and use the `podman auto-update` feature and systemd timer to get the same behavior as above (well, on a longer timescale by default. I think it checks at midnight by default), except the user can be completely unprivileged. Or not even have a password.

**Comment by solacelost** [comment]
In the interest in improving community adoption of what I view as a great FOSS accounting platform, I submitted a [pull request](https://github.com/akaunting/docker/pull/14). If you aren't happy with it, or with my GitHub history on my personal account, you don't need to accept it. Thanks for what you do, I'm going to keep running Akaunting!

**Comment by denisdulici** [comment]
@MohammedAl-Mahdawi has joined Akaunting team and is going to maintain this repo.
