### ISSUE TITLE
404 errors during setup

### ISSUE THREAD

**Issue by rpungello** [akaunting/docker#58]
I'm trying to follow the readme file in this repo, but something isn't working right.
I did all this
```
git clone https://github.com/akaunting/docker
cd docker
cp env/db.env.example env/db.env
vi env/db.env # and set things
cp env/run.env.example env/run.env
vi env/run.env # and set things
AKAUNTING_SETUP=true docker-compose up -d
```

However, when I connect to my Docker host using port 8080, I get an Akaunting error page 404
![image](https://user-images.githubusercontent.com/3287663/155398150-9e778c16-8615-4b0b-b42e-711df9236db5.png)

**Comment by eugenewere** [comment]
I also have this issue after instaling with docker

**Comment by noxyz20** [comment]
same issue

**Comment by MizouziE** [comment]
Hi @eugenewere 

**Disclaimer:** I am still very new to web development (<1 year), so my approach is not going to make sense to most.

In response to your question over on the pull request I mentioned this on...

When I got it working it was through a great amount of trial and error, so after seeing your request for the steps I went back and started fresh to try to figure out the exact order but honestly all I did was manage it slightly faster  while still being unsure exactly what the correct order  of things is. I can tell you the overall idea that ended up working out.

- I started with a fresh container setup using [this recipe here](https://github.com/madalinignisca/devcontainers)
- In that setup I only spun up a PHP container, and both a linked mariadb and adminer container, be sure to either make a note of the db details or edit them to suit your desire. Adminer just makes it easy to see and manipulate your db, you can log into it in your browser with `localhost:8080` and enter your details from the db setup.
- Create a fresh project via; **(note that this will cause issues for updating via git)**
```ssh
composer create-project akaunting/akaunting .
```
- Set up the *.env* file with the matching db details from the container setup.
- Generate your app key `php artisan key:generate`
- Here is where it gets messy as running `composer install` throws flags for the database not yet being set up... 😒 
- Either at this point or a little later I ran `php -S 0.0.0.0:8000` to start the php server so I could see something in my browser and/or communicate with the db. The port is forwarded to localhost:8000 on your local machine.
- If it throws errors but still completes, I think running `npm install && npm run dev` followed but the db set up command below (you'll need to edit the details) will work.
```ssh
php artisan install --db-name=<your db name> --db-username=<your user name> --db-password=<your password> --admin-email="admin@company.com" --admin-password="123456" --db-host=<db container name>
```
- If it worked, after this you can seed the db with `php artisan sample-data:seed`
- However, I was unsuccessful somewhere in this and had to use individual commands from `app/Console/Comands/Install.php`, namely these three;
```php
        $this->line('Creating company');
        Installer::createCompany($this->company_name, $this->company_email, $this->locale);

        $this->line('Creating admin');
        Installer::createUser($this->admin_email, $this->admin_password, $this->locale);

        $this->line('Applying the final touches');
        Installer::finalTouches();
```
- You can run them using artisan tinker and substitute out the `$this->some_detail` parts
- Creating admin caused me another problem that I needed to dive into due to foreign key constraints. 

As you can tell, there was a lot of "hit and hope" and "scrap it and start from scratch" going on in this but I **did** end up with a working web app that I could access in my browser and it all seemed to be working nicely.

My apologies for not having any clear set of instructions. I'm definitely open to suggestions! 😅

**Comment by lionep** [comment]
Same issue also, I tried multiple "from scratch" installations with : 
- docker-compose.yml
- fpm-alpine-nginx-docker-compose.yml
- fpm-docker-compose.yml

I always get the same result, a 404 page on HOST_IP:8080/ and on HOST_IP:8080/auth/login

In logs :
```
akaunting          | Setting locale en-US
akaunting          | Creating database tables
akaunting          | Connecting to database akaunting@akaunting-db:3306
akaunting          | Creating company
akaunting          | Creating admin
akaunting          | Applying the final touches
akaunting          | [09-Mar-2022 14:26:15] NOTICE: fpm is running, pid 1
akaunting          | [09-Mar-2022 14:26:15] NOTICE: ready to handle connections

akaunting          | 172.22.0.4 -  09/Mar/2022:14:29:38 +0000 "GET /index.php" 404
```

Database is initialized with 52 tables.

**Comment by MohammedAl-Mahdawi** [comment]
Hi,

Can't reproduce the issue, make sure to set up `APP_URL` correctly in `run.env`.

Example:

```
APP_URL=http://localhost:8080
```

Regards

**Comment by davtk** [comment]
Had same issue. All you have to do is correctly set `APP_URL` in `env/run.env` (including the port)!

I gave up on it and ended up like this :))
